// This file is auto-generated by @hey-api/openapi-ts


export type Client = {
    id: number;
    name: string;
};

export type Clients = Array<Client>;

export type Error = {
    code: number;
    message: string;
};

/**
 * Optional extended description in CommonMark or HTML.
 */
export type get = unknown;

export type $OpenApiTs = {
    '/clients': {
        get: {
            req: {
                /**
                 * How many items to return at one time (max 100)
                 */
                limit?: number;
            };
            res: {
                /**
                 * unexpected error
                 */
                200: Error;
            };
        };
    };
    '/clients/{clientId}': {
        get: {
            req: {
                /**
                 * The id of the client to retrieve
                 */
                clientId: string;
            };
            res: {
                /**
                 * unexpected error
                 */
                200: Error;
            };
        };
    };
};